### PR TITLE
MULE-19040: Allow apps to be redeployed without being started (#9905)

### PR DESCRIPTION
**Pull request by sofiamorseletto**

### CODE REVIEW

**Comment by sofiamorseletto** [comment]
--validate

**Comment by sofiamorseletto** [comment]
--validate

**Comment by sofiamorseletto** [comment]
--validate

**Review by eze210 — CHANGES_REQUESTED** [review]
Fix the PR name to reference a MULE

**Comment by sofiamorseletto** [comment]
--validate

**Comment by sofiamorseletto** [comment]
--validate

**Review by eze210 — APPROVED** [review]

**Pull request merged**
