### PR TITLE
W-14654712: avoid disposing `DataWeaveExpressionLanguageAdaptor`'s `ExpressionLanguage` if not initialised

### PR DESCRIPTION
**Pull request by rbourbonnavarro**

### CODE REVIEW

**Review by elrodro83 — APPROVED** [review]

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Pull request merged**
