### PR TITLE
W-12979787: Add trace/span id to the MDC so that the logs are related…

### PR DESCRIPTION
**Pull request by fsgonz**
… to the current Span when available

### CODE REVIEW

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Review by IvanAndresFritzler — DISMISSED** [review]

**Review by IvanAndresFritzler — APPROVED** [review]

**Pull request merged**
