### PR TITLE
MULE-19252: Use a RWLock in PersistentObjectStorePartition instead of

### PR DESCRIPTION
**Pull request by elrodro83**
synchronized blocks

### CODE REVIEW

**Review by marianogonzalez — APPROVED** [review]
LGTM. Such a shame the data structure we're using doesn't allow us to simply syncrhonize at the key level :(

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Pull request merged**
