### PR TITLE
W-14427994: Subflow location is not propagated in tracing. (#12977)

### PR DESCRIPTION
**Pull request by IvanAndresFritzler**

### CODE REVIEW

**Review by alopezbizon — APPROVED** [review]

**Review by sofiamorseletto — APPROVED** [review]

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Pull request merged**
