### PR TITLE
W-15294065: Remove dependency from artifact activation to runtime-extension-model

### PR DESCRIPTION
**Pull request by mbuchwald**

### CODE REVIEW

**Review by marianogonzalez — DISMISSED** [review]

**Review by marianogonzalez — APPROVED** [review]

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validaet

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Pull request merged**
