### PR TITLE
W-15894519: Deleting an App with DLL on Windows can cause a memory leak

### PR DESCRIPTION
**Pull request by alopezbizon**

### CODE REVIEW

**Review by fsgonz — APPROVED** [review]

**Comment by simonvalter** [comment]
hi, in mule 4.6.6 and 4.6.7 I experience a problem with restarting and redeploying a integration that uses the SAP connector on windows. Stop and Start works fine. Restart and Redeployment causes the jvm to crash with EXCEPTION_ACCESS_VIOLATION and it relates to the native sapjco dll being gone at the point of time something seems to still be using it. These changes seems to be a likely cause. I have attached the crash log

**Comment by simonvalter** [comment]
[hs_err_pid15816.log](https://github.com/user-attachments/files/16979497/hs_err_pid15816.log)

**Comment by fsgonz** [comment]
@simonvalter Hi, is this also happening in 4.6.6? Can you open a ticket with the support team?

**Comment by simonvalter** [comment]
Yes 4.6.6 and 4.6.7
I created a ticket with support on this issues, just digging a bit into the problem myself also.

**Comment by fsgonz** [comment]
We will be working on this to provide the fix in the next release. We apologize for the inconveniences. We will manage the communication through the support team.

**Comment by simonvalter** [comment]
Thanks!

**Pull request merged**
