### PR TITLE
W-16447481: Move ArtifactType to mule-api (#13709)

### PR DESCRIPTION
**Pull request by rbourbonnavarro**
(cherry picked from commit 109655ee4b634c14375ab38f06b11be0e55c3f8c)

### CODE REVIEW

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Review by eze210 — APPROVED** [review]

**Pull request merged**
