### PR TITLE
MULE-11727 - 

### PR DESCRIPTION
**Pull request by jorgeserrao**
Remove class All.java and remove element all from Mule.xsd schema

### CODE REVIEW

**Comment by pablokraan** [comment]
Thanks Jorge for your contribution.
I'm afraid that this PR is not enough to remove the "all" router. 
Is required to remove all the code that was used to support it and also update every test using it.
And don't forget to sign the contribution agreement

**Comment by jorgeserrao** [comment]
Hi Pablo,

I removed the classes where All.java was used.

Regarding the Contribuition Agreement, I'm getting an error while signing.

**Comment by pablokraan** [comment]
Thanks for the update.
We are making big changes on mule-4.x branch, on of these changes is that the integration tests that used to be on this repo were moved to https://github.com/mulesoft/mule-integration-tests.
And there are other aditional repositiories, which are not documented... as we had not time to update the documentation :(
So, to continue with this PR, there must be another one updating the integration tests to make them pass.

Regarding the agreement signup, show us the message you are getting so we can try to fix it.

**Comment by jorgeserrao** [comment]
Sorry Pablo but I'm unable to find that repository.

screen shot 2017-05-12 at 17 04 17

I also attached the error I'm getting for the Contribuitors Agreement.

screen shot 2017-05-12 at 17 06 07

**Comment by pablokraan** [comment]
Repository should be visible now.
I have no update regarding the agreement signup

**Comment by jorgeserrao** [comment]
Pablo, I didn't find any occurrence of All class in the test cases present in https://github.com/mulesoft/mule-integration-tests repository

**Comment by pablokraan** [comment]
Take a look at the configuration files used on the tests (tip: try to run all the test and see what happens)

**Comment by jorgeserrao** [comment]
I removed the All routing test cases and submitted a pull request:
https://github.com/mulesoft/mule-integration-tests/pull/30

**Comment by pablokraan** [comment]
Thanks Jorge,

These changes cannot be merged now, there are other private repositories that we will have to update. That will take some time as we are focused on other more critical tasks

**Comment by elrodro83** [comment]
This is accomplished now by https://github.com/mulesoft/mule/pull/5129

Thanks for your contribution anyway!

**Pull request closed without merging**
