### PR TITLE
W-16374984: Upgrade held back libraries because of dropped java 8 support

### PR DESCRIPTION
**Pull request by marianorean**

### CODE REVIEW

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Comment by marianorean** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Pull request merged**
