### PR TITLE
CMTS-87: Adopt fixes for OCS connection provider refresh token on Des…

### PR DESCRIPTION
**Pull request by gsfernandes**
…clarationSession services

### CODE REVIEW

**Review by svacas — APPROVED** [review]

**Comment by gsfernandes** [comment]
--validate

**Comment by gsfernandes** [comment]
--validate

**Comment by gsfernandes** [comment]
--validate

**Comment by gsfernandes** [comment]
--validate

**Comment by gsfernandes** [comment]
--validate

**Review by lucianoRM — APPROVED** [review]

**Pull request merged**
