### PR TITLE
W-12225580: [Tracer performance] Improve ComponentExecutionInitialSpa…

### PR DESCRIPTION
**Pull request by IvanAndresFritzler**
…nInfo performance

### CODE REVIEW

**Comment by IvanAndresFritzler** [comment]
--validate

**Review by sofiamorseletto — APPROVED** [review]

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Pull request merged**
