### PR TITLE
W-14463120: Macro expansion of complex parameters is making the AST mutate everytime it's read.

### PR DESCRIPTION
**Pull request by IvanAndresFritzler**

### CODE REVIEW

**Review by alopezbizon — APPROVED** [review]

**Review by elrodro83 — DISMISSED** [review]

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Comment by IvanAndresFritzler** [comment]
--validate

**Comment by IvanAndresFritzler** [comment]
--validate

**Pull request merged**
