### PR TITLE
W-14180661: Incorrect validation of expression support in OAuth connection provider models (#12837)

### PR DESCRIPTION
**Pull request by rbourbonnavarro**
(cherry picked from commit f0956411272adc939a954633bfba6ecf3055f285)

### CODE REVIEW

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Comment by rbourbonnavarro** [comment]
--validate

**Review by asanguinetti — APPROVED** [review]

**Pull request merged**
