### PR TITLE
W-13136310: NPE on scheduler due to propagation of distributed trace context

### PR DESCRIPTION
**Pull request by fsgonz**

### CODE REVIEW

**Comment by fsgonz** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Review by sofiamorseletto — APPROVED** [review]

**Review by IvanAndresFritzler — COMMENTED** [review]
We should also check if we can leverage this NoOp also with the sources that are not a scheduler but also do not receive a remote context.

**Review by IvanAndresFritzler — CHANGES_REQUESTED** [review]
Requesting changes (see previous comments).

**Review by IvanAndresFritzler — APPROVED** [review]

**Comment by fsgonz** [comment]
We've verify that for the cases of internal scheduler the callback context is created in a different way than in the sdk. I'll create a task to verify if that can be optimized.

**Pull request merged**
