### PR TITLE
MULE-18782: remove more deprecated code

### PR DESCRIPTION
**Pull request by mbuchwald**
We keep "global-functions" in the xsd definition for MEL compatibility, but DW does not have this

### CODE REVIEW

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Review by elrodro83 — DISMISSED** [review]

**Comment by mbuchwald** [comment]
--validate

**Review by elrodro83 — APPROVED** [review]

**Pull request closed without merging**
