### PR TITLE
W-12967303: Split packages between mule-module-properties-config and mule-module-spring-config

### PR DESCRIPTION
**Pull request by marianorean**

### CODE REVIEW

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Pull request merged**
