### PR TITLE
W-15750766: GroovyResourceReleaser - avoid unregistering classes that may belong to other artifacts

### PR DESCRIPTION
**Pull request by aronee2008**

### CODE REVIEW

**Comment by aronee2008** [comment]
--validate

**Comment by aronee2008** [comment]
--validate

**Review by rbourbonnavarro — DISMISSED** [review]

**Review by eze210 — APPROVED** [review]

**Comment by aronee2008** [comment]
-validate

**Review by eze210 — APPROVED** [review]

**Review by eze210 — APPROVED** [review]

**Comment by eze210** [comment]
--validate

**Pull request merged**
