### PR TITLE
MULE-16897: No primary node notification listener set on extension sources with cluster support

### PR DESCRIPTION
**Pull request by mbuchwald**

### CODE REVIEW

**Review by eze210 — APPROVED** [review]

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Pull request merged**
