### PR TITLE
EE-8188: Update log4j to 2.16.0

### PR DESCRIPTION
**Pull request by elrodro83**
* Includes MULE-17814: Infinite Loop when setting
-Dmule.classloading.verbose=true (#8509)

### CODE REVIEW

**Comment by elrodro83** [comment]
--valdiate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Review by aiannucci — APPROVED** [review]

**Pull request merged**
