### PR TITLE
W-11492976: A.3.2 Implement the production of units for Until Success…

### PR DESCRIPTION
**Pull request by sofiamorseletto**
…ful according to the spec A.3.1.

(cherry picked from commit dfbe4024a1d92abd72b17c0c60c6a0eee3a0af1f)

### CODE REVIEW

**Comment by sofiamorseletto** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Comment by sofiamorseletto** [comment]
--validate

**Comment by sofiamorseletto** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Review by fsgonz — APPROVED** [review]

**Pull request merged**
