### PR TITLE
MULE-20001: Typed value parameters are not decorated to be uncloseable

### PR DESCRIPTION
**Pull request by ndinu**

### CODE REVIEW

**Review by dabreu — APPROVED** [review]

**Comment by ndinu** [comment]
--validate

**Comment by ndinu** [comment]
--validate

**Comment by ndinu** [comment]
--validate

**Comment by ndinu** [comment]
--validate

**Comment by ndinu** [comment]
--validate

**Review by dabreu — APPROVED** [review]

**Pull request merged**
