### PR TITLE
MULE-8135: Comparator for SFTP-Transport

### PR DESCRIPTION
**Pull request by ChristianLangmann**
I've implemented a OlderFirstComparator for the SFTP-transporter similar to the File-Transport-implementation. (compare with PR 1280)

Same could be probably done for FTP, but FTP currently uses multiple threads for scheduling it's work so an ordering currently doesn't make sense.

### CODE REVIEW

**Comment by afelisatti** [comment]
Hey, Christian. Thanks for your collaboration! It seems there were some merge conflicts though that were not resolved (see SftpMessageReceiver for example). Please submit another PR after fixing that. Cheers!

**Comment by marcosnc** [comment]
Hi Christian, seems like there are unresolved conflicts from a merge, the first file in the PR is one from the new http module, I'm sure those changes are not part of your contribution. Please upgrade your local repository and review the merge. Regards.

**Comment by afelisatti** [comment]
Hi, Christian. It seems the fix for the merge errors generated 15 commits, please squash them into a single one. You will also have to merge our latest changes into your branch since it can no longer be automatically merged. You can find information on how to do all this in our contributors guide: https://github.com/mulesoft/mule/blob/mule-3.x/CONTRIBUTE.md . Thanks!

**Comment by vromero** [comment]
Hey @ChristianLangmann, any news around this?
We have to close this for inactivity unless you need more time. Please let us know if this is the case.
Thanks.

**Comment by ChristianLangmann** [comment]
Hi,

I’m struggling with compressing into only one commit…
Probably it’s easier to restart with the current mule-version, a fresh branch and reimplement the changes.

Please give me a few days so I can check how to do it...

Best regards
Christian

**Pull request closed without merging**
