### PR TITLE
Update Smack to 4.0.6

### PR DESCRIPTION
**Pull request by Flowdalic**
I'm aware that the changes to the method signatures regarding exceptions means an API breakage. I leave it up to the mule devs to decide how to proceed. Basically I see three options:

- Use the "new" API in the next major Mule version (that's my prefered solution)
- Use the "new" API in the current Mule version
- Wrap the exceptions so that the API stays the same

### CODE REVIEW

**Comment by vromero** [comment]
Hello @Flowdalic,

Thank you very much for this contribution and apologies around the belated reply,

The Mule transport system is pretty much designed around your third solution, there are a number of reasons for this but the ability to reconnect is an outstanding one.

Can I also ask you to take a look to the CONTRIBUTE.md and make sure to follow those suggestions? We really need a JIRA issue and the issue id in the commit description.

Thanks !

**Comment by vromero** [comment]
Hi @Flowdalic ,

Any news on this? we might need to close this for inactivity

**Comment by Flowdalic** [comment]
Free free to close. I have no obligations to pursue this further.

**Comment by afelisatti** [comment]
Closing for inactivity.

**Pull request closed without merging**
