### PR TITLE
added support for s390x architecture

### PR DESCRIPTION
**Pull request by prajakta-ibm**
added support for s390x architecture.

### CODE REVIEW

**Comment by aiannucci** [comment]
Hi @prajakta-ibm, thanks a lot for this contribution!
In order for us to be able to merge it, I need to ask you to please sign our contributors agreement by following this link:
https://api-notebook.anypoint.mulesoft.com/notebooks/#380297ed0e474010ff43

Please let me know when it is ready.

Thanks again!

**Comment by aiannucci** [comment]
jenkins validate

**Comment by aiannucci** [comment]
Unfortunately, this change is not sufficient for the wrapper to work on s390x architecture.
The wrapper version we ship with CE is 3.2.3 for now.
Support for zLinux on s390 and s390x was added in version 3.5.0 of the wrapper.
Support for IBM z/OS was added in version 3.3.9 of the wrapper.
Source: https://wrapper.tanukisoftware.com/doc/english/release-notes.html

**Comment by prajakta-ibm** [comment]
Hi aiannucci,
Should I create and provide a binary wrapper for s390x ?To add the binary, we may need to check with Tanukisoftwares, if adding the changes should be ok.
Thanks.

**Comment by aiannucci** [comment]
First of all, have you tested this change?
I'm afraid this will not be easy and that we should upgrade the whole wrapper. I will talk to the team about it.

**Comment by prajakta-ibm** [comment]
Hi aiannucci,

For 3.8.0 branch of mule, I have built the wrapper for s390x architetcure from source available in sourceforge repository .
The wrapper was copied to appropriate location in mule directory structure and was tested with HelloWorld example successfully.
Let me know incase any further details are required.

Thanks.

**Comment by pablokraan** [comment]
As long as I know, adding s390x in the mule script is not enough to be able to run on a s390 system, you will need an additional wrapper library which is not part of this PR.
But... we are not going to include a library that you built from some sources found on the internet. We can rely only on the libraries provided by Tanuki.

**Pull request closed without merging**
