### PR TITLE
Mule 3.6.2 - Dates should be independent of locale settings

### PR DESCRIPTION
**Pull request by basmussen**

### CODE REVIEW

**Comment by dfeist** [comment]
Is there a JIRA issue for this describing the problem?

**Comment by basmussen** [comment]
TestCase breaks down if the default locale is not en_US. Issue affects all mule branches.

**Comment by marianogonzalez** [comment]
Hello @basmussen , thank you for this contribution.

There're some formalities we need to go through before we can go on and merge this pull request.

1) First, please review our contributors agreement at this link http://www.mulesoft.org/legal/contributor-agreement.html
2) Then, please accept that agreement by running this script https://api-notebook.anypoint.mulesoft.com/notebooks#bc1cf75a0284268407e4
3) Lastly, per our contribution guide (which you can review here https://github.com/mulesoft/mule/blob/mule-3.x/CONTRIBUTE.md), we require that:
   * A jira issue is created describing the problem you're fixing or feature you're adding
   * Squash your two commits into a single one, which message should have the following format MULE-XXXX: <<issue title here>>

Please let us know if you have any questions and thank you again for contributing with the project.

**Comment by basmussen** [comment]
JIRA issue MULE-8436. New PR created https://github.com/mulesoft/mule/pull/1524

**Pull request closed without merging**
