### PR TITLE
EE-7372: Verify is application is deployed looking into logs (#9290)

### PR DESCRIPTION
**Pull request by mlischetti**
(cherry picked from commit e0b76ee3e3eb85bcfeb27773e486a3fb5688020b)

### CODE REVIEW

**Review by szaffarano — DISMISSED** [review]

**Comment by mlischetti** [comment]
--validate

**Comment by mlischetti** [comment]
--validate

**Comment by mlischetti** [comment]
--validate

**Comment by mlischetti** [comment]
--validate

**Comment by mlischetti** [comment]
--validate

**Comment by mlischetti** [comment]
--validate

**Comment by fsgonz** [comment]
--validate

**Pull request closed without merging**
