### PR TITLE
W-14350781: Enable GroovyResourceReleaser for each JDK. Removing incorrect cleaning method. (#12979)

### PR DESCRIPTION
**Pull request by eze210**
(cherry picked from commit 42898a955426e0a6746eb1f1e9b0480b8c8a0eb6)

### CODE REVIEW

**Review by asanguinetti — APPROVED** [review]

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Pull request merged**
