### PR TITLE
W-14202319: (Addendum) Adding missing "requires" in module-info (#13033)

### PR DESCRIPTION
**Pull request by eze210**
(cherry picked from commit c72aeaec2b9ca92bac4e89d03ed331c472e7214e)

### CODE REVIEW

**Review by elrodro83 — APPROVED** [review]

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Comment by eze210** [comment]
--validate

**Pull request merged**
