### PR TITLE
W-17218707: Serializer error in Java 17 with Kryo and Clustering or Object Store v2 (#14022)

### PR DESCRIPTION
**Pull request by akshaysonvane**
* W-17218707: Serializer error in Java 17 with Kryo and Clustering or Object Store v2

* address comments

### CODE REVIEW

**Comment by akshaysonvane** [comment]
--validate

**Comment by akshaysonvane** [comment]
--validate

**Comment by akshaysonvane** [comment]
--validate

**Comment by akshaysonvane** [comment]
--validate

**Review by eze210 — APPROVED** [review]

**Comment by akshaysonvane** [comment]
--validate

**Pull request merged**
