### PR TITLE
MULE-10230: Allow SQL variable assignment operator

### PR DESCRIPTION
**Pull request by MaxOcklind**
https://www.mulesoft.org/jira/browse/MULE-10230

### CODE REVIEW

**Comment by pablokraan** [comment]
Hi @MaxOcklind, thanks for sending this PR. 
Can you add tests to ensure your change works as expected on SimpleQueryTemplateParserTestCase?

**Comment by marianogonzalez** [comment]
shouldn't this PR point to the 3.x branch?

**Comment by MaxOcklind** [comment]
Hi @pablokraan, I have now added a test case.

Do you agree with @marianogonzalez that this PR should be pointed at the 3.x branch? And in that case I'm guessing that I need to checkout that branch, make the changes again and create a new PR? (I'm new to git and github so expect a stupid question or two)

**Comment by pablokraan** [comment]
@MaxOcklind yes, the PR against mule-3.x makes more sense. The changes are probably to be the same but the class you changed is going to be in a different package. Don't forget to check the code format before pushing the changes.

**Comment by pablokraan** [comment]
I'm closing this PR as there is another one created on mule-3.x branch

**Pull request closed without merging**
