### PR TITLE
W-14202319: Configure required opens in each service instead of having them hardcoded in mule code

### PR DESCRIPTION
**Pull request by elrodro83**
* Modularize modules/deployment tests
* Modularize mock services
* Adapt test java compiler for using modules

### CODE REVIEW

**Review by mbuchwald — DISMISSED** [review]

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Review by mbuchwald — APPROVED** [review]

**Comment by elrodro83** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Comment by mbuchwald** [comment]
--validate

**Pull request merged**
