### PR TITLE
W-11798994: Provide an isolated messaged counter that resets on every…

### PR DESCRIPTION
**Pull request by elrodro83**
… query (#11801)

### CODE REVIEW

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Review by marianogonzalez — APPROVED** [review]

**Pull request merged**
