### PR TITLE
W-16188357: Mule Runtime is unable to find properties files at /lib/user (#13677)

### PR DESCRIPTION
**Pull request by marianorean**
(cherry picked from commit bc0086ea32e4740ef8d6f2304801b70fc97dbc6b)

### CODE REVIEW

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Comment by marianorean** [comment]
--validate

**Review by elrodro83 — APPROVED** [review]

**Pull request merged**
