### PR TITLE
W-14398600: Mule Runtime 4.5 changed logic for Shared Libraries for Design Operations (#12964)

### PR DESCRIPTION
**Pull request by elrodro83**

### CODE REVIEW

**Review by rbourbonnavarro — APPROVED** [review]

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Comment by elrodro83** [comment]
--validate

**Pull request merged**
