### PR TITLE
Jira Issue Mule-9562 mule udp connector is creating new socket object for same address

### PR DESCRIPTION
**Pull request by cpsinghal**
mule udp connector is  creating new socket object for same address. Currently it passing endpoint. I have create UdpSocketKey class  & now passing UdpSocketKey class object.

I have tested. It is working fine.

### CODE REVIEW

**Comment by cpsinghal** [comment]
This is still open after 2 days. no action taken?

**Comment by asequeira** [comment]
Hello, sorry for the delayed response.
Can you use for the commit message this format: MULE-9562 + Issue summary?

**Comment by cpsinghal** [comment]
Hi asequeira,

I have commited with MULE-9562 + Issue summary. Can you look now?

**Comment by cpsinghal** [comment]
any update?

**Comment by aiannucci** [comment]
Hi,

I'm closing this as the related JIRA is closed, it was fixed in the mule-4.x branch and targeted for 4.0 release.

**Pull request closed without merging**
